// <auto-generated />
namespace VisiNoti.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class visimobile_notification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(visimobile_notification));
        
        string IMigrationMetadata.Id
        {
            get { return "201804051309161_visimobile_notification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
